version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - moneyger_network

  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    command: ["./moneyger"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - moneyger_network

volumes:
  db_data:

networks:
  moneyger_network:
