name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpass
          POSTGRES_DB: development
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.2

    - name: List contents of Go workspace
      run: ls -la $GITHUB_WORKSPACE

    - name: Initialize Go module
      run: |
        cd $GITHUB_WORKSPACE
        go mod init github.com/zVitorSantos/Moneyger-Backend || true
        go mod tidy

    - name: Build Docker image
      run: docker build -t moneyger-backend -f deployments/Dockerfile .

    - name: Run tests
      run: docker run --rm --network host -v ${{ github.workspace }}:/app -w /app moneyger-backend go test -v -coverprofile=coverage.out ./...

    - name: Check if coverage file exists
      run: ls -la coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        flags: unittests
        name: codecov-report
